### ISSUE TITLE
Code Review of Hashtables

### ISSUE THREAD

**Issue by SWHarrison** [imthaghost/tweetGen#3]
- Great job adding new tests to check the robustness of your code! Make sure you check the indentation of your new tests, it was off when I checked it.
- Nice work adding functions to make it iterable. A great next step is to add functions such as ```__getitem__``` so that your hash table can be used like python's dictionary object.
- I took a look through your commented out implementation, great job working on resizing! I encourage you to look into alternate hash collision resolution strategies if you want to further your understanding of how to create efficient hash tables.
- The average case run time for contains, set, get and delete is not fully explained. Remember that load factor is what determines average run time, as each bucket will contain roughly n/b items, or L.

**Comment by imthaghost** [comment]
Thanks bro! I'll be sure to take your advice and improve my code!
